// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PretriageWeb.Models;

namespace PretriageWeb.Migrations
{
    [DbContext(typeof(PretriageDB))]
    [Migration("20200713180407_Mig1")]
    partial class Mig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PretriageWeb.Models.ConfigModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Kod_Produktu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Liczba_Jednostek_Roz")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa_Produktu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Wartosc_Jednostki")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("ConfigModels");
                });

            modelBuilder.Entity("PretriageWeb.Models.PretriageModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Data_Do")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Data_Od")
                        .HasColumnType("datetime2");

                    b.Property<string>("Kod_Produktu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Liczba_Jednostek_Roz")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa_Produktu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pesel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Wartosc")
                        .HasColumnType("float");

                    b.Property<double>("Wartosc_Jednostki")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("PretriageModels");
                });
#pragma warning restore 612, 618
        }
    }
}
