// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PretriageWeb.Models;

namespace PretriageWeb.Migrations
{
    [DbContext(typeof(PretriageDB))]
    partial class PretriageDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PretriageWeb.Models.ConfigModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Kod_Produktu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Liczba_Jednostek_Roz")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa_Produktu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<double>("Wartosc_Jednostki")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Config");
                });

            modelBuilder.Entity("PretriageWeb.Models.PretriageModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataWpisu")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Data_Do")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Data_Od")
                        .HasColumnType("datetime2");

                    b.Property<string>("InnyDokument")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kod_Produktu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Liczba_Jednostek_Roz")
                        .HasColumnType("int");

                    b.Property<string>("Miejsce")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwa_Produktu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumerSeria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pesel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<double>("Wartosc")
                        .HasColumnType("float");

                    b.Property<double>("Wartosc_Jednostki")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Pretriage");
                });

            modelBuilder.Entity("PretriageWeb.Models.UnitModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Unit");
                });

            modelBuilder.Entity("PretriageWeb.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HashPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
